### ISSUE TITLE
Inconsistencies with macros

### ISSUE THREAD

**Issue by 3-w-c** [jlquinn/xbows-driver#23]
With the below test file, only "Z" (macro 0) works, pressing A and Q does nothing (no output in `evtest` or `xev`).

Or am I misunderstanding how they're meant to work?

```
layer: custom 3

keymap:
  Z: { macro: 0 }
  A: { macro: 1 }
  Q: { macro: 2 }

macros:
  - id: 0
    mode: once
    steps:
      - X down
      - 5 ms
      - X up
  - id: 1
    mode: once
    steps:
      - C down
      - 5 ms
      - C up
  - id: 2
    mode: once
    steps:
      - V down
      - 5 ms
      - V up
```
